### ISSUE TITLE
Regularization parameter for single test location

### ISSUE THREAD

**Issue by marcoadurno** [wittawatj/interpretable-test#3]
Hi,

When using a single test location the code throws at:
https://github.com/wittawatj/interpretable-test/blob/master/freqopttest/tst.py#L1230

This is because the regularization parameter is set to 'auto' and there is no logic to handle it (unlike the case n_features > 1, https://github.com/wittawatj/interpretable-test/blob/master/freqopttest/tst.py#L1232)

Best Regards,

Marco

**Comment by wittawatj** [comment]
Thanks for your comment, Marco. You are right. When J=1, use reg=0 for now. I will patch it today.

**Comment by wittawatj** [comment]
I quickly fixed it. Please let me know if it works now. :)

**Comment by marcoadurno** [comment]
Hi,

I quickly tried it out and all is good now.

Many thanks. And congratulations for the nice work!

Best Regards,

Marco

**Comment by wittawatj** [comment]
Thanks very much!
